name: Deploy to Azure VM

on:
  push:
    branches:
      - main # Ganti sesuai branch kamu

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup SSH
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.AZURE_SSH_KEY }}

      - name: Deploy to Azure VM
        run: |
          ssh -o StrictHostKeyChecking=no ${{ secrets.AZURE_USER }}@${{ secrets.AZURE_HOST }} << 'EOF'
            cd ${{ secrets.AZURE_REPO_PATH }}
            sudo git pull
            sudo npm install
            sudo npm run build

            sudo rm -rf ${ secrets.AZURE_DEPLOY_PATH }/*
            sudo mv dist/* ${{ secrets.AZURE_DEPLOY_PATH }}
            sudo systemctl restart nginx
          EOF
